name: alphacy

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Chrome Stable
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Python dependencies
        run: |
          pip3 install selenium selenium-stealth

      - name: Run script
        run: |
          cd core/platforms
          python3 alphacy.py

      - name: Commit only if changed
        run: |
          if git diff --quiet; then
            echo "No changes detected — skipping commit"
          else
            echo "Changes detected — committing"
            git add -A
            git commit -m "streams updated"
            git push
          fi
