name: alphacy streams

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install -U playwright
          playwright install chromium

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Update Bot"

      - name: Grab alphacy stream
        working-directory: ./core/platforms
        run: |
          python3 alphacy.py > ../../streams/alphacy.m3u8

      - name: Commit & Push changes
        run: |
          git add -A
          git commit -m "alphacy stream updated" || echo "No changes"
          git push
